name: Scrape and Update Contribution List

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install cheerio

      - name: Scrape href links
        id: scrape_links
        run: |
          url="https://github.com/pulls?q=is%3Apr+is%3Amerged+author%3Ajaivardhan-bhola"
          links=$(curl -s "$url" | pup 'a[data-hovercard-type="repository"] attr{href}' | sort -u)
          echo "::set-output name=links::$links"

      - name: Update README
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const links = `${{ steps.scrape_links.outputs.links }}`;
            const contributionList = `<!-- CONTRIBUTION-LIST:START -->\n${links}\n<!-- CONTRIBUTION-LIST:END -->\n`;
            const readmePath = `${process.env.GITHUB_WORKSPACE}/README.md`;
            let readmeContent = fs.readFileSync(readmePath, 'utf8');
            readmeContent = readmeContent.replace(/<!-- CONTRIBUTION-LIST:START -->(.|\n)*<!-- CONTRIBUTION-LIST:END -->/, contributionList);
            console.log(contributionList));
            fs.writeFileSync(readmePath, readmeContent);

