name: Update Contribution List

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-contribution-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Scrape repository links
        run: node extract-links.js
        id: scrape_links

      - name: Check links
        run: node check-links.js

      - name: Generate contribution list
        run: node generate-contribution-list.js
        env:
          LINKS: ${{ steps.scrape_links.outputs.links }}

      - name: Update README
        run: |
          const fs = require('fs');
          const readmePath = `${process.env.GITHUB_WORKSPACE}/README.md`;
          let readmeContent = fs.readFileSync(readmePath, 'utf8');
          readmeContent = readmeContent.replace(/<!-- CONTRIBUTION-LIST:START -->(.|\n)*<!-- CONTRIBUTION-LIST:END -->/, process.env.CONTRIBUTION_LIST);
          console.log(process.env.CONTRIBUTION_LIST);
          fs.writeFileSync(readmePath, readmeContent);

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Update contribution list"
          git push