name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch contribution list
        id: fetch_contributions
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: 'fetch-contributions'
          client-payload: '{"username": "jaivardhan-bhola"}'

      - name: Update README
        run: |
          echo "<!-- CONTRIBUTION-LIST:START -->" > README.md
          echo "${{ steps.fetch_contributions.outputs.repositories }}" >> README.md
          echo "<!-- CONTRIBUTION-LIST:END -->" >> README.md
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Update README.md"
          git push